### ISSUE TITLE
hi I had some problem. Can you help me?

### ISSUE THREAD

**Issue by LinCh83** [yysijie/st-gcn#10]
I want to train the model by myself.
but I run this code python main.py --config config/st_gcn/nturgbd-cross-subject/train.yaml

I get  this error message
RuntimeError: invalid argument 1: must be strictly positive at c:\anaconda2\conda-bld\pytorch_1519496000060\work\torch\lib\th\generic/THTensorMath.c:2247

Can you tell me what happened?
And How can I fix it?
Thank you.

**Comment by LinCh83** [comment]
hi I fix this problem
I reload my NTU-RGB-D dataset
It is work
But I had the new problem when I train the model
"OverflowError: cannot serialize a bytes object larger than 4 GiB"
Is it possible that my GPU is too old?
I only GT 740 in my device. 
So Pytorch not supprt?
Thank you help

**Comment by yysijie** [comment]
Hi, LinCh,
Can you give me more details such as which sentence results in this error?

**Comment by LinCh83** [comment]
Hi, yysijie.
Thank you for your reply.
This is all the error messages.
[ Tue Mar 27 09:41:31 2018 ] Training epoch: 1
Traceback (most recent call last):
  File "main.py", line 426, in <module>
    processor.start()
  File "main.py", line 371, in start
    self.train(epoch, save_model=save_model)
  File "main.py", line 283, in train
    for batch_idx, (data, label) in enumerate(loader):
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 234, in __init__
    w.start()
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OverflowError: cannot serialize a bytes object larger than 4 GiB

And the warning he say
Found GPU0 GeForce GT 740 which is of cuda capability 3.0.
PyTorch no longer supports this GPU because it is too old.

So I guess the problem that my device is too old.
What's your opinion? 
Thank you

**Comment by yysijie** [comment]
Thank you for the detailed information.
If you can run the test code correctly, we can rule out the possibility that GPUs are too old.
But I have not tested my code on Windows System. The Win32 System or the python version you used may not support storing files larger than 4GB, which will cause this error. Try to modify the config file, use the test set (which is small) as the training set.
