### ISSUE TITLE
I can't run it correctly

### ISSUE THREAD

**Issue by RDSJC** [yysijie/st-gcn#148]
### Code version (Git Hash) and PyTorch version
0.1.0 1.0.1
### Expected behavior
I hope it will run correctly
### Actual behavior
But it didn't
### Steps to reproduce the behavior

Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
OpenPose demo successfully finished. Total time: 289.994776 seconds.
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    p.start()
  File "/root/st-gcn/processor/demo.py", line 47, in start
    video = utils.video.get_video_frames(self.arg.video)
  File "/root/st-gcn/tools/utils/video.py", line 33, in get_video_frames
    vread = skvideo.io.vread(video_path)
  File "/usr/local/lib/python3.5/dist-packages/skvideo/io/io.py", line 147, in vread
    videodata = np.zeros((T, M, N, C), dtype=np.uint8)
MemoryError

**Comment by Txj8811** [comment]
Try to run a shorter video

**Comment by CompliceU** [comment]
can i complie the openpose with python2 ,but use st-gcn with python3?thx

**Comment by Txj8811** [comment]
@CompliceU I think you can. There is no envrionmental relation between st-gcn and openpose.

**Comment by CompliceU** [comment]
@Txj8811 But I want to make a show, show the teacher to use the camera to do the work, isn't it necessary to use openpose to do some work? Sorry, not very understanding

**Comment by Txj8811** [comment]
@CompliceU I can’t understand your words of ‘ use the camera to do the work’. Use camera to make a real-time version of st-gcn ?

**Comment by CompliceU** [comment]
@Txj8811 Yes, it is best to do this, or use your own video to complete this demo, do not know how to configure, I hope to get your help

**Comment by Txj8811** [comment]
@CompliceU well, you can run the st-gcn demo by your own video firstly.

**Comment by zz-ycx** [comment]
hello, i can run your video demo successfully, but i want to know how to run a video stream with a camera.could you give me some advice about it?

**Comment by Txj8811** [comment]
I'm also interested in the way of real-time method. I have set up a communication between openpose and st-gcn, use a sliding window to run the model. But it seems that the window sizes and steps depended on the trainned videos. The result looks ok, but is there a better way to do this?

**Comment by CompliceU** [comment]
@Txj8811 yeah ,i know it can work well,but i always lose when i complie the openpose with python3,hoho

**Comment by Txj8811** [comment]
@CompliceU follow the openpose doc/installation.md. no problem.

**Comment by zz-ycx** [comment]
@Txj8811 i try to save the openpose output and then recall fixed number frames to st-gcn to recognize ,but it seems not so good

**Comment by RDSJC** [comment]
@Txj8811 I am also interested in real-time method and I wonder that if the st-gcn support it

**Comment by xiehaizheng** [comment]
@Txj8811  I am also interested in real-time method .you said  you  have set up a communication between openpose and st-gcn, use a sliding window to run the model.Can I refer to your work?

**Comment by Txj8811** [comment]
@xiehaizheng 时间隔的有点久了...可以联系我的wechat：txj8811，我可以给一些思路上的帮助。

**Comment by wyz0916-gitHub** [comment]
> hello, i can run your video demo successfully, but i want to know how to run a video stream with a camera.could you give me some advice about it?

Hi，I have just contact it.How to install the openpose python-api?
