### ISSUE TITLE
执行main.py显示DLL load failed

### ISSUE THREAD

**Issue by liwanjie1020** [yysijie/st-gcn#161]
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import torchlight
  File "E:\Anaconda\lib\site-packages\torchlight-1.0-py3.6.egg\torchlight\__init__.py", line 1, in <module>
    from .io import IO
  File "E:\Anaconda\lib\site-packages\torchlight-1.0-py3.6.egg\torchlight\io.py", line 20, in <module>
    import h5py
  File "E:\Anaconda\lib\site-packages\h5py\__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py\h5r.pxd", line 21, in init h5py._conv
  File "h5py\_objects.pxd", line 12, in init h5py.h5r
  File "h5py\_objects.pyx", line 1, in init h5py._objects
ImportError: DLL load failed: 找不到指定的程序。

**Comment by yysijie** [comment]
Hi, @liwanjie1020,  you did not install the h5py package correctly.
