### ISSUE TITLE
CUDA runtime error

### ISSUE THREAD

**Issue by DeH40** [yysijie/st-gcn#181]
### Code version (Git Hash) and PyTorch version
        pytorch version:1.0.1   code version:latest
### Other comments

Pose estimation complete.

Network forwad...
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    p.start()
  File "/home/test/st-gcn-master/processor/demo.py", line 71, in start
    output, feature = self.model.extract_feature(data)
  File "/home/test/st-gcn-master/net/st_gcn.py", line 98, in extract_feature
    x = x.permute(0, 4, 3, 1, 2).contiguous()
RuntimeError: CUDA error: invalid device function

My GPU is GT705

**Comment by DeH40** [comment]
sudo python3 main.py demo --openpose /usr/openpose/build --video /home/test/VID_20190506_093552.avi 
[sudo] test 的密码： 
/home/test/st-gcn-master/processor/io.py:39: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  default_arg = yaml.load(f)
/usr/local/lib/python3.5/dist-packages/torch/cuda/__init__.py:117: UserWarning: 
    Found GPU0 GeForce GT 705 which is of cuda capability 2.1.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Empty frame detected, frame number 43 of 44. In /usr/openpose/src/openpose/producer/producer.cpp:checkFrameIntegrity():285
Empty frame detected, frame number 43 of 44. In /usr/openpose/src/openpose/producer/producer.cpp:checkFrameIntegrity():285
Empty frame detected, frame number 43 of 44. In /usr/openpose/src/openpose/producer/producer.cpp:checkFrameIntegrity():285
OpenPose demo successfully finished. Total time: 20.257288 seconds.
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000023_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000015_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000001_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000002_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000033_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000024_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000041_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000029_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000025_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000009_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000010_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000027_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000028_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000004_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000018_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000030_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000037_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000020_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000034_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000008_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000040_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000039_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000019_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000005_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000038_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000016_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000014_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000013_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000000_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000032_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000006_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000031_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000012_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000007_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000026_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000021_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000017_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000011_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000003_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000035_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000022_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000042_keypoints.json
data/openpose_estimation/snippets/VID_20190506_093552/VID_20190506_093552_000000000036_keypoints.json
Pose estimation complete.

Network forwad...
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    p.start()
  File "/home/test/st-gcn-master/processor/demo.py", line 71, in start
    output, feature = self.model.extract_feature(data)
  File "/home/test/st-gcn-master/net/st_gcn.py", line 98, in extract_feature
    x = x.permute(0, 4, 3, 1, 2).contiguous()
RuntimeError: CUDA error: invalid device function

**Comment by ITdoubleseven** [comment]
hello,did you solve this problem?I got the same problem with you,maybe.

**Comment by JasOlean** [comment]
@DeH40 
You should add "--device 0" at last in your command.
