### ISSUE TITLE
Problem when loading pretrained model?

### ISSUE THREAD

**Issue by hufengshuo07** [yysijie/st-gcn#182]
Thank you for your brilliant work. Could you help me with this problem when trying demo? I've re-downloaded models from both baiduyun and get_models.sh

sure@sure-ThinkStation-P318:~/文档/sure/pose/activity_recognition/st-gcn-master$ python3 main.py demo --openpose ../../openpose/build/ --video ./resource/media/skateboarding.mp4
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torchlight-1.0-py3.5.egg/torchlight/io.py", line 82, in load_weights
    __doc__ = _io._TextIOBase.__doc__
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
	Unexpected key(s) in state_dict: "data_bn.num_batches_tracked", "st_gcn_networks.0.tcn.0.num_batches_tracked", "st_gcn_networks.0.tcn.3.num_batches_tracked", "st_gcn_networks.1.tcn.0.num_batches_tracked", "st_gcn_networks.1.tcn.3.num_batches_tracked", "st_gcn_networks.2.tcn.0.num_batches_tracked", "st_gcn_networks.2.tcn.3.num_batches_tracked", "st_gcn_networks.3.tcn.0.num_batches_tracked", "st_gcn_networks.3.tcn.3.num_batches_tracked", "st_gcn_networks.4.tcn.0.num_batches_tracked", "st_gcn_networks.4.tcn.3.num_batches_tracked", "st_gcn_networks.4.residual.1.num_batches_tracked", "st_gcn_networks.5.tcn.0.num_batches_tracked", "st_gcn_networks.5.tcn.3.num_batches_tracked", "st_gcn_networks.6.tcn.0.num_batches_tracked", "st_gcn_networks.6.tcn.3.num_batches_tracked", "st_gcn_networks.7.tcn.0.num_batches_tracked", "st_gcn_networks.7.tcn.3.num_batches_tracked", "st_gcn_networks.7.residual.1.num_batches_tracked", "st_gcn_networks.8.tcn.0.num_batches_tracked", "st_gcn_networks.8.tcn.3.num_batches_tracked", "st_gcn_networks.9.tcn.0.num_batches_tracked", "st_gcn_networks.9.tcn.3.num_batches_tracked".

**Comment by arthur-k-kochi** [comment]
Looks similar to my case and the issue #49 .
Try running `sudo apt-get install ffmpeg`

**Comment by PrettyZZW** [comment]
i have same error but install ffmpeg can't solve this problem
[06.19.19|02:24:21] Load weights [edge_importance.7].
[06.19.19|02:24:21] Load weights [edge_importance.8].
[06.19.19|02:24:21] Load weights [edge_importance.9].
[06.19.19|02:24:21] Load weights [fcn.weight].
[06.19.19|02:24:21] Load weights [fcn.bias].
Traceback (most recent call last):
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torchlight-1.0-py3.6.egg/torchlight/io.py", line 82, in load_weights
    __doc__ = _io._TextIOBase.__doc__
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
	Unexpected key(s) in state_dict: "data_bn.num_batches_tracked", "st_gcn_networks.0.tcn.0.num_batches_tracked", "st_gcn_networks.0.tcn.3.num_batches_tracked", "st_gcn_networks.1.tcn.0.num_batches_tracked", "st_gcn_networks.1.tcn.3.num_batches_tracked", "st_gcn_networks.2.tcn.0.num_batches_tracked", "st_gcn_networks.2.tcn.3.num_batches_tracked", "st_gcn_networks.3.tcn.0.num_batches_tracked", "st_gcn_networks.3.tcn.3.num_batches_tracked", "st_gcn_networks.4.tcn.0.num_batches_tracked", "st_gcn_networks.4.tcn.3.num_batches_tracked", "st_gcn_networks.4.residual.1.num_batches_tracked", "st_gcn_networks.5.tcn.0.num_batches_tracked", "st_gcn_networks.5.tcn.3.num_batches_tracked", "st_gcn_networks.6.tcn.0.num_batches_tracked", "st_gcn_networks.6.tcn.3.num_batches_tracked", "st_gcn_networks.7.tcn.0.num_batches_tracked", "st_gcn_networks.7.tcn.3.num_batches_tracked", "st_gcn_networks.7.residual.1.num_batches_tracked", "st_gcn_networks.8.tcn.0.num_batches_tracked", "st_gcn_networks.8.tcn.3.num_batches_tracked", "st_gcn_networks.9.tcn.0.num_batches_tracked", "st_gcn_networks.9.tcn.3.num_batches_tracked".

**Comment by punknownq** [comment]
I have the same problem.

**Comment by alike123** [comment]
+1. Have you solved this problem?

**Comment by daylightsaving2017** [comment]
I have solved this problem and verified the reason by some experiments. This problem is due to the version compatibilty of the PyTorch. If you use a newer version to train a model, the old version pytorch often cannot load it.

**Comment by daylightsaving2017** [comment]
@hufengshuo07 @arthur-k-kochi @PrettyZZW @punknownq @alike123 
You can download a fixed model from the repo provided by one developer in a similar issue.
links here: 
https://pan.baidu.com/s/1JrfpRqt0uF8AydiJuxANZw
password:j4rt
Duplicate of #172
Thanks for the work by @XJX777

**Comment by peter-yys-yoon** [comment]
> @hufengshuo07 @arthur-k-kochi @PrettyZZW @punknownq @alike123
> You can download a fixed model from the repo provided by one developer in a similar issue.
> links here:
> https://pan.baidu.com/s/1JrfpRqt0uF8AydiJuxANZw
> password:j4rt
> Duplicate of #172
> Thanks for the work by @XJX777

Could you share the weight files?
I tried to download them from baidu, but it doesn't work.
