### ISSUE TITLE
import torchlight err

### ISSUE THREAD

**Issue by lovehuanhuan** [yysijie/st-gcn#183]
>>> import torchlight
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\ProgramData\Anaconda2\envs\python3\lib\site-packages\torchlight-1.0-py3.6.egg\torchlight\__init__.py", line 1, in <module>
  File "E:\ProgramData\Anaconda2\envs\python3\lib\site-packages\torchlight-1.0-py3.6.egg\torchlight\io.py", line 13, in <module>
    BufferedIOBase deals with buffering on a raw byte stream (RawIOBase). Its

**Comment by daylightsaving2017** [comment]
@lovehuanhuan I highly suggest that you'd better conduct experiments on Ubuntu16.04 OS. It is testified that many problems and errors occured on WIndows OS.
Hints: Pls install torchlight as author‘s instructions of README.md document before any other operations.
