### ISSUE TITLE
How to convert the .pt models to .pb model

### ISSUE THREAD

**Issue by kfcbla** [yysijie/st-gcn#188]

**Comment by daylightsaving2017** [comment]
The similar question as above including how to convert to .onnx model.

**Comment by qualia0000** [comment]
Similar problem on converting .pt model to .onnx model. After loading the .pt model, I executed:
`example = torch.ones(3, 1, 18, 1)
example = example.unsqueeze(0)
example = example.float().to(device).detach()    
torch.onnx.export(model, example, "onnx_model_80.onnx")`
Then I got following error:
`Traceback (most recent call last):
  File "c:\Users\xiaosong\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\xiaosong\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\xiaosong\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "D:\ProgramData\Miniconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\ProgramData\Miniconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\ProgramData\Miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\source\python3-xint-pipeline\convert_to_onnx.py", line 35, in <module>
    torch.onnx.export(model, example, "onnx_model_80.onnx", verbose=True, input_names=input_names, output_names=output_names)
  File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 131, in export
    strip_doc_string=strip_doc_string)
  File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 278, in _model_to_graph
    _disable_torch_constant_prop=_disable_torch_constant_prop)
  File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\__init__.py", line 50, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 602, in _run_symbolic_function
    n.kindOf("value")))
RuntimeError: Unsupported prim::Constant kind: `s`. Send a bug report.`
I am aware that the function `torch.onnx.export` should contain params called `input_names` and `output_names` but I got difficulty acquring them in the net.
Could you give any advise on it? Thank you.
