### ISSUE TITLE
RuntimeError: CUDA error: invalid argument

### ISSUE THREAD

**Issue by zyj0021200** [yysijie/st-gcn#200]
hello,when I run "python main.py recognition -c config/st_gcn/kinetics-skeleton/test.yaml",the following error occurred:
[06.20.19|20:28:58] Load weights from ./models/st_gcn.kinetics.pt.
[06.20.19|20:28:58] Load weights [A].
[06.20.19|20:28:58] Load weights [data_bn.weight].
[06.20.19|20:28:58] Load weights [data_bn.bias].
[06.20.19|20:28:58] Load weights [data_bn.running_mean].
[06.20.19|20:28:58] Load weights [data_bn.running_var].
[06.20.19|20:28:58] Load weights [data_bn.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.gcn.conv.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.gcn.conv.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.tcn.0.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.tcn.0.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.tcn.0.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.tcn.0.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.tcn.0.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.tcn.2.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.tcn.2.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.tcn.3.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.tcn.3.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.tcn.3.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.tcn.3.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.0.tcn.3.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.gcn.conv.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.gcn.conv.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.tcn.0.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.tcn.0.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.tcn.0.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.tcn.0.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.tcn.0.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.tcn.2.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.tcn.2.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.tcn.3.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.tcn.3.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.tcn.3.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.tcn.3.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.1.tcn.3.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.gcn.conv.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.gcn.conv.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.tcn.0.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.tcn.0.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.tcn.0.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.tcn.0.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.tcn.0.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.tcn.2.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.tcn.2.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.tcn.3.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.tcn.3.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.tcn.3.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.tcn.3.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.2.tcn.3.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.gcn.conv.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.gcn.conv.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.tcn.0.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.tcn.0.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.tcn.0.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.tcn.0.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.tcn.0.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.tcn.2.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.tcn.2.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.tcn.3.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.tcn.3.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.tcn.3.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.tcn.3.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.3.tcn.3.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.gcn.conv.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.gcn.conv.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.tcn.0.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.tcn.0.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.tcn.0.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.tcn.0.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.tcn.0.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.tcn.2.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.tcn.2.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.tcn.3.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.tcn.3.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.tcn.3.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.tcn.3.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.tcn.3.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.residual.0.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.residual.0.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.residual.1.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.residual.1.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.residual.1.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.residual.1.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.4.residual.1.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.gcn.conv.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.gcn.conv.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.tcn.0.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.tcn.0.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.tcn.0.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.tcn.0.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.tcn.0.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.tcn.2.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.tcn.2.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.tcn.3.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.tcn.3.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.tcn.3.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.tcn.3.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.5.tcn.3.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.gcn.conv.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.gcn.conv.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.tcn.0.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.tcn.0.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.tcn.0.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.tcn.0.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.tcn.0.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.tcn.2.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.tcn.2.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.tcn.3.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.tcn.3.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.tcn.3.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.tcn.3.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.6.tcn.3.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.gcn.conv.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.gcn.conv.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.tcn.0.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.tcn.0.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.tcn.0.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.tcn.0.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.tcn.0.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.tcn.2.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.tcn.2.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.tcn.3.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.tcn.3.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.tcn.3.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.tcn.3.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.tcn.3.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.residual.0.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.residual.0.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.residual.1.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.residual.1.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.residual.1.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.residual.1.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.7.residual.1.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.gcn.conv.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.gcn.conv.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.tcn.0.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.tcn.0.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.tcn.0.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.tcn.0.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.tcn.0.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.tcn.2.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.tcn.2.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.tcn.3.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.tcn.3.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.tcn.3.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.tcn.3.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.8.tcn.3.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.gcn.conv.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.gcn.conv.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.tcn.0.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.tcn.0.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.tcn.0.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.tcn.0.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.tcn.0.num_batches_tracked].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.tcn.2.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.tcn.2.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.tcn.3.weight].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.tcn.3.bias].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.tcn.3.running_mean].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.tcn.3.running_var].
[06.20.19|20:28:58] Load weights [st_gcn_networks.9.tcn.3.num_batches_tracked].
[06.20.19|20:28:58] Load weights [edge_importance.0].
[06.20.19|20:28:58] Load weights [edge_importance.1].
[06.20.19|20:28:58] Load weights [edge_importance.2].
[06.20.19|20:28:58] Load weights [edge_importance.3].
[06.20.19|20:28:58] Load weights [edge_importance.4].
[06.20.19|20:28:58] Load weights [edge_importance.5].
[06.20.19|20:28:58] Load weights [edge_importance.6].
[06.20.19|20:28:58] Load weights [edge_importance.7].
[06.20.19|20:28:58] Load weights [edge_importance.8].
[06.20.19|20:28:58] Load weights [edge_importance.9].
[06.20.19|20:28:58] Load weights [fcn.weight].
[06.20.19|20:28:58] Load weights [fcn.bias].
[06.20.19|20:28:58] Parameters:
{'work_dir': './work_dir/tmp', 'config': 'config/st_gcn/kinetics-skeleton/test.yaml', 'phase': 'test', 'save_result': False, 'start_epoch': 0, 'num_epoch': 80, 'use_gpu': True, 'device': 0, 'log_interval': 100, 'save_interval': 10, 'eval_interval': 5, 'save_log': True, 'print_log': True, 'pavi_log': False, 'feeder': 'feeder.feeder.Feeder', 'num_worker': 4, 'train_feeder_args': {'debug': False}, 'test_feeder_args': {'data_path': './data/Kinetics/kinetics-skeleton/val_data.npy', 'label_path': './data/Kinetics/kinetics-skeleton/val_label.pkl'}, 'batch_size': 256, 'test_batch_size': 64, 'debug': False, 'model': 'net.st_gcn.Model', 'model_args': {'in_channels': 3, 'num_class': 400, 'edge_importance_weighting': True, 'graph_args': {'layout': 'openpose', 'strategy': 'spatial'}}, 'weights': './models/st_gcn.kinetics.pt', 'ignore_weights': [], 'show_topk': [1, 5], 'base_lr': 0.01, 'step': [], 'optimizer': 'SGD', 'nesterov': True, 'weight_decay': 0.0001}

[06.20.19|20:28:58] Model:   net.st_gcn.Model.
[06.20.19|20:28:58] Weights: ./models/st_gcn.kinetics.pt.
[06.20.19|20:28:58] Evaluation Start:
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    p.start()
  File "/home/njuciairs/HAQ/st-gcn/processor/processor.py", line 139, in start
    self.test()
  File "/home/njuciairs/HAQ/st-gcn/processor/recognition.py", line 126, in test
    output = self.model(data)
  File "/home/njuciairs/InstallTools/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/njuciairs/HAQ/st-gcn/net/st_gcn.py", line 77, in forward
    x = x.permute(0, 1, 3, 4, 2).contiguous()
RuntimeError: CUDA error: invalid argument
why this occurred and how to solve this problem?
looking forward to your reply--

**Comment by wardpeng** [comment]
Hi,

@zyj0021200 I have same error on my sider.
Do you solve it now? Thanks a lot

BR,
Ward
