### ISSUE TITLE
HELP!OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by liurui16** [yysijie/st-gcn#29]
### Code version (Git Hash) and PyTorch version
Python 3.6.4 |Anaconda custom (64-bit)
dual system: windows & ubuntu
Nvidia GeForce GTX 950M
### Dataset used
NTU RGB+D
### Expected behavior
cross-view evaluation in NTU RGB+D,run the code:
python main.py --config config/st_gcn/nturgbd-cross-view/test.yaml
### Actual behavior
[ Fri Apr 20 17:44:22 2018 ] Load weights from ./model/ntuxview-st_gcn.pt.
[ Fri Apr 20 17:44:22 2018 ] Model:   st_gcn.net.ST_GCN.
[ Fri Apr 20 17:44:22 2018 ] Weights: ./model/ntuxview-st_gcn.pt.
[ Fri Apr 20 17:44:22 2018 ] Eval epoch: 1
Traceback (most recent call last):
  File "main.py", line 426, in <module>
    processor.start()
  File "main.py", line 388, in start
    epoch=0, save_score=self.arg.save_score, loader_name=['test'])
  File "main.py", line 335, in eval
    for batch_idx, (data, label) in enumerate(self.data_loader[ln]):
  File "/home/rui/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 310, in __iter__
    return DataLoaderIter(self)
  File "/home/rui/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 167, in __init__
    w.start()
  File "/home/rui/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/rui/anaconda3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/rui/anaconda3/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/rui/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 26, in __init__
    self._launch(process_obj)
  File "/home/rui/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    self.pid = os.fork()
[ Fri Apr 20 17:44:22 2018 ] Load weights from ./model/ntuxview-st_gcn.pt.
[ Fri Apr 20 17:44:22 2018 ] Model:   st_gcn.net.ST_GCN.
[ Fri Apr 20 17:44:22 2018 ] Weights: ./model/ntuxview-st_gcn.pt.
[ Fri Apr 20 17:44:22 2018 ] Eval epoch: 1
Traceback (most recent call last):
  File "main.py", line 426, in <module>
    processor.start()
  File "main.py", line 388, in start
    epoch=0, save_score=self.arg.save_score, loader_name=['test'])
  File "main.py", line 335, in eval
    for batch_idx, (data, label) in enumerate(self.data_loader[ln]):
  File "/home/rui/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 310, in __iter__
    return DataLoaderIter(self)
  File "/home/rui/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 167, in __init__
    w.start()
  File "/home/rui/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/rui/anaconda3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/rui/anaconda3/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/rui/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 26, in __init__
    self._launch(process_obj)
  File "/home/rui/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by yjxiong** [comment]
Haven't met this error before. Few things I suggest to check:
1. ulimit
2. PyTorch version < 0.4
3. shared memory size

**Comment by liurui16** [comment]
Really appreciate for your help.
I don't exactly know where the problem is.
I fixed it by setting the"num_workers = 0",then it finally worked.
Wish you best!

**Comment by yjxiong** [comment]
num_workers=0 means you are running without any data prefetching, which is slow. Usually this kind of error is due to 
1. ulimit
2. shared memory
I don't which one corresponds to your case here
