### ISSUE TITLE
EOFError during Testing Pretrained Models

### ISSUE THREAD

**Issue by liurui16** [yysijie/st-gcn#31]
HI!@yysijie @yjxiong 
Thanks for your great work!
I'm studying your work,but I came up with some problems as follows,could you please give me some hints?
### Code version (Git Hash) and PyTorch version
I USE Docker which contains:
===================== module list ===================
python 3.6 (apt) # torch latest (git) # chainer latest (pip) # cntk 2.3 (pip) # jupyter latest (pip) # mxnet latest (pip) # pytorch 0.3.0 (pip) # tensorflow latest (pip) # theano latest (git) # keras latest (pip) # lasagne latest (git) # opencv latest (git) # sonnet latest (pip) # caffe latest (git) # ==================================================
### Dataset used
NTU RGB+D
### Expected behavior
Testing Pretrained Models
run the code python `main.py --config config/st_gcn/kinetics-skeleton/test.yaml`
### Actual behavior
root@eb6f3da57874:/data1/st-gcn/st-gcn-master# python main.py --config config/st_gcn/kinetics-skeleton/test.yaml
[ Mon Apr 23 10:08:30 2018 ] Load weights from ./model/kinetics-st_gcn.pt.
[ Mon Apr 23 10:08:31 2018 ] Model:   st_gcn.net.ST_GCN.
[ Mon Apr 23 10:08:31 2018 ] Weights: ./model/kinetics-st_gcn.pt.
[ Mon Apr 23 10:08:31 2018 ] Eval epoch: 1
Process Process-8:
Process Process-23:
Process Process-22:
Process Process-25:
Process Process-21:
Process Process-24:
Process Process-2:
Process Process-5:
Process Process-13:
Process Process-7:
Process Process-14:
Process Process-11:
Process Process-12:
Process Process-35:
Process Process-32:
Process Process-31:
Process Process-19:
Process Process-28:
Process Process-30:
Process Process-33:
Process Process-16:
Process Process-26:
Process Process-18:
Process Process-27:
Process Process-29:
Process Process-15:
Process Process-50:
Process Process-51:
Process Process-45:
Process Process-44:
Process Process-46:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 46, in _worker_loop
    data_queue.put((idx, samples))
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/reductions.py", line 113, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_140_3440579072> at /pytorch/torch/lib/TH/THAllocator.c:319
.....  
with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
### Steps to reproduce the behavior
I got  pretrained models and both two datasets are ready

**Comment by yjxiong** [comment]
```
fd, size = storage.share_fd()
RuntimeError: unable to write to file </torch_140_3440579072> at /pytorch/torch/lib/TH/THAllocator.c:319
```

Did you follow the PyTorch's instruction to set `--ipc=host` when you launch your docker image?

**Comment by yjxiong** [comment]
@liurui16 Any updates?
