### ISSUE TITLE
Run it on CPU

### ISSUE THREAD

**Issue by AndrewSoul** [yysijie/st-gcn#33]
### Code version (Git Hash) and PyTorch version
Python 3.6.4 |Anaconda 3(64-bit)|pytorch 0.3.1.post2' CPU
dual system: windows & ubuntu

### Dataset used
kinectics-skeleton

### Expected behavior
Run the code on CPU environment 

### Actual behavior
python main.py --config config/st_gcn/kinetics-skeleton/test.yaml
Traceback (most recent call last):
  File "main.py", line 425, in <module>
    processor = Processor(arg)
  File "main.py", line 155, in __init__
    self.load_model()
  File "main.py", line 178, in load_model
    self.model = Model(**self.arg.model_args).cuda(output_device)
  File "/home/extend/PycharmProjects/st-gcn-master/st_gcn/net/st_gcn.py", line 71, in __init__
    self.A = torch.from_numpy(self.graph.A).float().cuda(0)
  File "/etc/Anaconda3/envs/pytorch-env/lib/python3.6/site-packages/torch/_utils.py", line 61, in _cuda
    with torch.cuda.device(device):
  File "/etc/Anaconda3/envs/pytorch-env/lib/python3.6/site-packages/torch/cuda/__init__.py", line 207, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'

### Steps to reproduce the behavior
Data prepared and model downloaded, after running  python main.py --config config/st_gcn/kinetics-skeleton/test.yaml, I got this Attribute Error.

**Comment by yjxiong** [comment]
This codebase is not written for running on CPU. If you do need it, try remove all cuda related function calls.
