### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by AndrewSoul** [yysijie/st-gcn#34]
Thanks for your great work~ I try to run this code, but I have met some problem.

### Code version (Git Hash) and PyTorch version
Python 3.6.3 |Anaconda 3(64-bit)|pytorch 0.3.0
system: ubuntu16.04 LTS

### Dataset used
kinectics-skeleton

### Expected behavior
Evaluation

### Actual behavior
python main.py --config config/st_gcn/kinetics-skeleton/test.yaml

[ Thu May  3 20:01:10 2018 ] Load weights from ./model/kinetics-st_gcn.pt.
[ Thu May  3 20:01:10 2018 ] Model:   st_gcn.net.ST_GCN.
[ Thu May  3 20:01:10 2018 ] Weights: ./model/kinetics-st_gcn.pt.
[ Thu May  3 20:01:10 2018 ] Eval epoch: 1
Traceback (most recent call last):
  File "main.py", line 426, in <module>
    processor.start()
  File "main.py", line 388, in start
    epoch=0, save_score=self.arg.save_score, loader_name=['test'])
  File "main.py", line 344, in eval
    output = self.model(data)
  File "/home/andrew/anaconda3/envs/pytorch-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/extended/st-gcn-master/st_gcn/net/st_gcn.py", line 150, in forward
    x = self.gcn0(x)
  File "/home/andrew/anaconda3/envs/pytorch-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/extended/st-gcn-master/st_gcn/net/unit_gcn.py", line 70, in forward
    self.A = self.A.cuda(x.get_device())
RuntimeError: get_device is not implemented for type torch.FloatTensor

### Steps to reproduce the behavior
After running  python main.py --config config/st_gcn/kinetics-skeleton/test.yaml, I got this RuntimeError

**Comment by yavana** [comment]
我也遇到类似问题，在win7上报错：

D:\redmine\st-gcn>python main.py --config config/st_gcn/kinetics-skeleton/test.y
aml
[ Tue May  8 09:27:18 2018 ] Load weights from ./model/kinetics-st_gcn.pt.
[ Tue May  8 09:27:19 2018 ] Model:   st_gcn.net.ST_GCN.
[ Tue May  8 09:27:19 2018 ] Weights: ./model/kinetics-st_gcn.pt.
[ Tue May  8 09:27:19 2018 ] Eval epoch: 1
Traceback (most recent call last):
  File "main.py", line 426, in <module>
    processor.start()
  File "main.py", line 388, in start
    epoch=0, save_score=self.arg.save_score, loader_name=['test'])
  File "main.py", line 335, in eval
    for batch_idx, (data, label) in enumerate(self.data_loader[ln]):
  File "D:\Program Files\Anaconda3\lib\site-packages\torch\utils\data\dataloader
.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "D:\Program Files\Anaconda3\lib\site-packages\torch\utils\data\dataloader
.py", line 239, in __init__
    w.start()
  File "D:\Program Files\Anaconda3\lib\multiprocessing\process.py", line 105, in
 start
    self._popen = self._Popen(self)
  File "D:\Program Files\Anaconda3\lib\multiprocessing\context.py", line 212, in
 _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Program Files\Anaconda3\lib\multiprocessing\context.py", line 313, in
 _Popen
    return Popen(process_obj)
  File "D:\Program Files\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", li
ne 66, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Program Files\Anaconda3\lib\multiprocessing\reduction.py", line 59, i
n dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument

**Comment by zhezh** [comment]
@AndrewSoul  try using nvidia-smi to check your cuda driver and cuda device
@yavana pytorch0.3 is not officially supported

**Comment by yjxiong** [comment]
@yavana 
Windows is only supported with PyTorch>0.4. We only support PyTorch version == 0.2

**Comment by AndrewSoul** [comment]
@zhezh  @yjxiong Thanks for your reply.
 My cuda driver and  cuda device are set well.  torch.cuda.is_available() returns True. And  the version of pytorch is 0.3.0.
