### ISSUE TITLE
Crashes with maybe some empty buffer error

### ISSUE THREAD

**Issue by rohitgirdhar** [yysijie/st-gcn#4]
The training starts off fine but crashes with the following error after some iterations:
```
[ Thu Jan 25 14:23:24 2018 ] Training epoch: 1
[ Thu Jan 25 14:27:41 2018 ]    Batch(0/940) done. Loss: 6.3487  lr:0.100000
[ Thu Jan 25 14:36:03 2018 ]    Batch(100/940) done. Loss: 5.6673  lr:0.100000
[ Thu Jan 25 14:44:26 2018 ]    Batch(200/940) done. Loss: 5.4984  lr:0.100000
[ Thu Jan 25 14:52:48 2018 ]    Batch(300/940) done. Loss: 5.3150  lr:0.100000
Traceback (most recent call last):
  File "main.py", line 426, in <module>
    processor.start()
  File "main.py", line 371, in start
    self.train(epoch, save_model=save_model)
  File "main.py", line 298, in train
    loss.backward()
  File "/home/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/anaconda2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: torch/csrc/autograd/input_buffer.cpp:14: add: Assertion `pos >= 0 && pos < buffer.size()` failed.
```
Wondering if anyone has seen this before? I'm training on Kinetics-skeletons data downloaded from the provided link.

**Comment by yysijie** [comment]
Could you show me the command you used?

**Comment by yysijie** [comment]
It seems a bug which randomly occurs in the Pytorch v0.3.0. See https://github.com/pytorch/pytorch/issues/3883
This bug has been fixed in the latest HEAD of Pytorch but there has not been a release version.
Or you can install Pytorch v0.2.0 which is working well on my servers.

**Comment by rohitgirdhar** [comment]
Oh I see.. thanks for looking into it!
