### ISSUE TITLE
val_label.pkl have not found

### ISSUE THREAD

**Issue by lucheng07082221** [yysijie/st-gcn#50]
when I run this command python main.py recognition -c config/st_gcn/kinetics-skeleton/test.yam
the val_label.pkl have not found
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    p = Processor(sys.argv[2:])
  File "/home/lc/Downloads/st-gcn/processor/processor.py", line 33, in __init__
    self.load_data()
  File "/home/lc/Downloads/st-gcn/processor/processor.py", line 62, in load_data
    dataset=Feeder(**self.arg.test_feeder_args),
  File "/home/lc/Downloads/st-gcn/feeder/feeder.py", line 48, in __init__
    self.load_data(mmap)
  File "/home/lc/Downloads/st-gcn/feeder/feeder.py", line 54, in load_data
    with open(self.label_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/Kinetics/kinetics-skeleton/val_label.pkl'

**Comment by alirezamosh** [comment]
I have got this error before.
*.pkl file will be generated by running :
`python tools/kinetics_gendata.py --data_path <path to kinetics-skeleton>`
Either you have not run this code or the generated *.pkl file is not in the path it is supposed to be.

**Comment by yjxiong** [comment]
@alirezamosh Thanks.

Closing this. Please feel free to reopen it if you meet any further problem.
