### ISSUE TITLE
libcaffe.so.1.0.0: cannot open shared object file

### ISSUE THREAD

**Issue by Mitchell1314** [yysijie/st-gcn#51]
Hi,
   I tried to run "python3.6 main.py demo --openpose /home/action-recognition/openpose/build" on my computer,but it failed:
![2018-06-14 22-21-53](https://user-images.githubusercontent.com/15179223/41417986-60351bd8-7021-11e8-97da-6f751c8d3a28.png)
Can you help me? How can I fix it?
By the way,openpose can be used successfully:
![2018-06-14 22-23-35](https://user-images.githubusercontent.com/15179223/41418091-9c3acb32-7021-11e8-8352-0b4e89140b2b.png)

**Comment by yysijie** [comment]
Hi, @Mitchell1314,
I hole this link would be useful for you.
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/148

**Comment by Mitchell1314** [comment]
Hi ,
   Thanks for your reply, and I have fixed the problem. But i met another problem when I run "python3.6 main.py recognition -c config/st_gcn/kinetics-skeleton/test.yaml", error information are as follows:
[06.17.18|17:29:27] Load weights from ./models/kinetics-st_gcn.pt.
[06.17.18|17:29:27] Load weights [A].
[06.17.18|17:29:27] Load weights [data_bn.weight].
[06.17.18|17:29:27] Load weights [data_bn.bias].
[06.17.18|17:29:27] Load weights [data_bn.running_mean].
[06.17.18|17:29:27] Load weights [data_bn.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.0.gcn.conv.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.0.gcn.conv.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.0.tcn.0.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.0.tcn.0.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.0.tcn.0.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.0.tcn.0.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.0.tcn.2.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.0.tcn.2.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.0.tcn.3.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.0.tcn.3.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.0.tcn.3.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.0.tcn.3.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.1.gcn.conv.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.1.gcn.conv.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.1.tcn.0.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.1.tcn.0.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.1.tcn.0.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.1.tcn.0.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.1.tcn.2.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.1.tcn.2.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.1.tcn.3.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.1.tcn.3.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.1.tcn.3.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.1.tcn.3.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.2.gcn.conv.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.2.gcn.conv.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.2.tcn.0.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.2.tcn.0.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.2.tcn.0.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.2.tcn.0.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.2.tcn.2.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.2.tcn.2.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.2.tcn.3.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.2.tcn.3.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.2.tcn.3.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.2.tcn.3.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.3.gcn.conv.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.3.gcn.conv.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.3.tcn.0.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.3.tcn.0.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.3.tcn.0.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.3.tcn.0.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.3.tcn.2.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.3.tcn.2.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.3.tcn.3.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.3.tcn.3.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.3.tcn.3.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.3.tcn.3.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.gcn.conv.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.gcn.conv.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.tcn.0.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.tcn.0.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.tcn.0.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.tcn.0.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.tcn.2.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.tcn.2.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.tcn.3.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.tcn.3.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.tcn.3.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.tcn.3.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.residual.0.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.residual.0.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.residual.1.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.residual.1.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.residual.1.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.4.residual.1.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.5.gcn.conv.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.5.gcn.conv.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.5.tcn.0.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.5.tcn.0.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.5.tcn.0.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.5.tcn.0.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.5.tcn.2.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.5.tcn.2.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.5.tcn.3.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.5.tcn.3.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.5.tcn.3.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.5.tcn.3.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.6.gcn.conv.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.6.gcn.conv.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.6.tcn.0.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.6.tcn.0.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.6.tcn.0.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.6.tcn.0.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.6.tcn.2.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.6.tcn.2.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.6.tcn.3.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.6.tcn.3.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.6.tcn.3.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.6.tcn.3.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.gcn.conv.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.gcn.conv.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.tcn.0.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.tcn.0.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.tcn.0.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.tcn.0.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.tcn.2.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.tcn.2.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.tcn.3.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.tcn.3.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.tcn.3.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.tcn.3.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.residual.0.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.residual.0.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.residual.1.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.residual.1.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.residual.1.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.7.residual.1.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.8.gcn.conv.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.8.gcn.conv.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.8.tcn.0.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.8.tcn.0.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.8.tcn.0.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.8.tcn.0.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.8.tcn.2.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.8.tcn.2.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.8.tcn.3.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.8.tcn.3.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.8.tcn.3.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.8.tcn.3.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.9.gcn.conv.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.9.gcn.conv.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.9.tcn.0.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.9.tcn.0.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.9.tcn.0.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.9.tcn.0.running_var].
[06.17.18|17:29:27] Load weights [st_gcn_networks.9.tcn.2.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.9.tcn.2.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.9.tcn.3.weight].
[06.17.18|17:29:27] Load weights [st_gcn_networks.9.tcn.3.bias].
[06.17.18|17:29:27] Load weights [st_gcn_networks.9.tcn.3.running_mean].
[06.17.18|17:29:27] Load weights [st_gcn_networks.9.tcn.3.running_var].
[06.17.18|17:29:27] Load weights [edge_importance.0].
[06.17.18|17:29:27] Load weights [edge_importance.1].
[06.17.18|17:29:27] Load weights [edge_importance.2].
[06.17.18|17:29:27] Load weights [edge_importance.3].
[06.17.18|17:29:27] Load weights [edge_importance.4].
[06.17.18|17:29:27] Load weights [edge_importance.5].
[06.17.18|17:29:27] Load weights [edge_importance.6].
[06.17.18|17:29:27] Load weights [edge_importance.7].
[06.17.18|17:29:27] Load weights [edge_importance.8].
[06.17.18|17:29:27] Load weights [edge_importance.9].
[06.17.18|17:29:27] Load weights [fcn.weight].
[06.17.18|17:29:27] Load weights [fcn.bias].
[06.17.18|17:29:37] Parameters:
{'work_dir': './work_dir/tmp', 'config': 'config/st_gcn/kinetics-skeleton/test.yaml', 'phase': 'test', 'save_result': False, 'start_epoch': 0, 'num_epoch': 80, 'device': 0, 'log_interval': 100, 'save_interval': 10, 'eval_interval': 5, 'save_log': True, 'print_log': True, 'pavi_log': False, 'feeder': 'feeder.feeder.Feeder', 'num_worker': 4, 'train_feeder_args': {'debug': False}, 'test_feeder_args': {'data_path': './data/Kinetics/kinetics-skeleton/val_data.npy', 'label_path': './data/Kinetics/kinetics-skeleton/val_label.pkl'}, 'batch_size': 256, 'test_batch_size': 64, 'debug': False, 'model': 'net.st_gcn.Model', 'model_args': {'in_channels': 3, 'num_class': 400, 'edge_importance_weighting': True, 'graph_args': {'layout': 'openpose', 'strategy': 'spatial'}}, 'weights': './models/kinetics-st_gcn.pt', 'ignore_weights': [], 'show_topk': [1, 5], 'base_lr': 0.01, 'step': [], 'optimizer': 'SGD', 'nesterov': True, 'weight_decay': 0.0001}

[06.17.18|17:29:37] Model:   net.st_gcn.Model.
[06.17.18|17:29:37] Weights: ./models/kinetics-st_gcn.pt.
[06.17.18|17:29:37] Evaluation Start:
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    p.start()
  File "/home/action-recognition/st-gcn/processor/processor.py", line 139, in start
    self.test()
  File "/home/action-recognition/st-gcn/processor/recognition.py", line 118, in test
    for data, label in loader:
  File "/home/action-recognition/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "/home/action-recognition/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 239, in __init__
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

By the way, my system information is as follows:
![2018-06-17 18-01-36](https://user-images.githubusercontent.com/15179223/41506864-83326864-7258-11e8-94a4-03438c04bfb7.png)
How can I fix this problem? Waiting for your reply!

**Comment by taxuezcy** [comment]
I meet the same question,can you tell me how you fix it ,thank you @Mitchell1314

**Comment by Mitchell1314** [comment]
Can your openpose run successfully? I mean run "./build/examples/openpose/openpose.bin --video examples/media/video.avi"

**Comment by taxuezcy** [comment]
yes, i can run  openpose  successfully @Mitchell1314

**Comment by yysijie** [comment]
@Mitchell1314, 
The data loader loads all data at the beginning by default, which requires more than 4GB memory in total. We fixed that in the latest master branch. You can update to the latest version to fix this problem.
Or just run below command at the old version to block above operation:
`python3.6 main.py recognition -c config/st_gcn/kinetics-skeleton/test.yaml --test_feeder_args mmap=True`

**Comment by yysijie** [comment]
@taxuezcy, 
Have you tried this solution?
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/148

**Comment by taxuezcy** [comment]
I have solved this problem ,thank you ! @yysijie

**Comment by yysijie** [comment]
@taxuezcy. Great!

**Comment by taxuezcy** [comment]
@Zzoey ,according to [CMU-Perceptual-Computing-Lab/openpose#148](url),you should find where is the libcaffe.so.1.0.0,and set the corresponding path, like 'export LD_LIBRARY_PATH=/home/cloud/openpose/3rdparty/caffe/.build_release/lib/:$LD_LIBRARY_PATH'

**Comment by Zzoey** [comment]
@taxuezcy Thanks fixed it but I get this new error, Any idea
Prototxt file not found: models/pose/body_25/pose_deploy.prototxt.

**Comment by taxuezcy** [comment]
@Zzoey  i don't have the prototxt file , have you downloaded the latest code?

**Comment by Zzoey** [comment]
Yes latest master version, @taxuezcy

**Comment by Zzoey** [comment]
@taxuezcy were you able to fix this, if I may ask? https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/668

**Comment by Zzoey** [comment]
I am on linux as well, unable to use openpose in this project. :(

**Comment by taxuezcy** [comment]
what's the problem you meet by using openpose? @Zzoey

**Comment by Zzoey** [comment]
Openpose is running perfectly fine but not st-gcn. I pasted the error above
