### ISSUE TITLE
error during training 

### ISSUE THREAD

**Issue by nilili89** [yysijie/st-gcn#57]

**Comment by nilili89** [comment]
Hello,
thank you for the wonderful work.
I test your demo, and also done the evaluation, but we I go on for the training processing it report a error as below:
[06.28.18|10:36:59] Training epoch: 0
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    p.start()
  File "/home/nll/st-gcn-master/processor/processor.py", line 113, in start
    self.train()
  File "/home/nll/st-gcn-master/processor/recognition.py", line 84, in train
    for data, label in loader:
  File "/home/nll/anaconda2/envs/pytorch3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "/home/nll/anaconda2/envs/pytorch3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 239, in __init__
    w.start()
  File "/home/nll/anaconda2/envs/pytorch3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/nll/anaconda2/envs/pytorch3.6/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/nll/anaconda2/envs/pytorch3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/nll/anaconda2/envs/pytorch3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/nll/anaconda2/envs/pytorch3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory



and this is my available memory
(pytorch3.6) nll@hq-System-Product-Name:~/st-gcn-master$ free -m
              total        used        free      shared  buff/cache   available
Mem:          31843        3031       28098         161         713       28166
Swap:         47682       40856        6826
I have two gpus so i set the device as gpus[0,1]
could you kindly info that where is the issue come form? 
And a further more question, I'm about to  train a new action by use your  work, I have prepared the dataset, unlike yours, you have 300 frame in each clips, I got about 1200 in each frame and I have produced the train and val binary documents, my question is with the size of train data, two gpus with 32G memory is available or not ? Thank you again for your great research work.

**Comment by nilili89** [comment]
I have fix the problem with upload your recently fixed code, but still need help for the data preparing issue,thanks a lot

**Comment by yysijie** [comment]
@nilili89,
Thank you for your interest in our work.
In the latest version, we load data by memory-mapping from disk by default. So, generally, the memory requirement will not be the bottleneck.

**Comment by nilili89** [comment]
Hello, I produced my own dataset which is just one position, so 'num_class'=1. But i get this problem as below.
Could you give me a hand. I think it is because there is a denominator equal to 0. but when I read your code I can't find where comes this problem.
[07.03.18|11:35:55] Parameters:
{'work_dir': './work_dir/recognition/kinetics_skeleton/ST_GCN', 'config': 'config/st_gcn/kinetics-skeleton/train.yaml', 'phase': 'train', 'save_result': False, 'start_epoch': 0, 'num_epoch': 60, 'use_gpu': True, 'device': [0, 1], 'log_interval': 100, 'save_interval': 10, 'eval_interval': 5, 'save_log': True, 'print_log': True, 'pavi_log': False, 'feeder': 'feeder.feeder.Feeder', 'num_worker': 2, 'train_feeder_args': {'random_choose': True, 'random_move': True, 'window_size': 150, 'data_path': './data/Kinetics/kinetics/train_data.npy', 'label_path': './data/Kinetics/kinetics/train_label.pkl', 'debug': False}, 'test_feeder_args': {'data_path': './data/Kinetics/kinetics/val_data.npy', 'label_path': './data/Kinetics/kinetics/val_label.pkl'}, 'batch_size': 256, 'test_batch_size': 256, 'debug': False, 'model': 'net.st_gcn.Model', 'model_args': {'in_channels': 3, 'num_class': 1, 'edge_importance_weighting': True, 'graph_args': {'layout': 'openpose', 'strategy': 'spatial'}}, 'weights': None, 'ignore_weights': [], 'show_topk': [1, 5], 'base_lr': 0.001, 'step': [20, 30, 40, 50], 'optimizer': 'SGD', 'nesterov': True, 'weight_decay': 0.0001}

[07.03.18|11:35:55] Training epoch: 0
/home/nll/anaconda2/envs/pytorch3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/nll/anaconda2/envs/pytorch3.6/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
[07.03.18|11:35:55] 	mean_loss: nan
[07.03.18|11:35:55] Time consumption:
[07.03.18|11:35:55] Done.
[07.03.18|11:35:55] Training epoch: 1
[07.03.18|11:35:55] 	mean_loss: nan
[07.03.18|11:35:55] Time consumption:
[07.03.18|11:35:55] Done.
[07.03.18|11:35:55] Training epoch: 2
[07.03.18|11:35:55] 	mean_loss: nan
[07.03.18|11:35:55] Time consumption:
[07.03.18|11:35:55] Done.
[07.03.18|11:35:55] Training epoch: 3
[07.03.18|11:35:55] 	mean_loss: nan
[07.03.18|11:35:55] Time consumption:
[07.03.18|11:35:55] Done.
[07.03.18|11:35:55] Training epoch: 4
[07.03.18|11:35:55] 	mean_loss: nan
[07.03.18|11:35:55] Time consumption:
[07.03.18|11:35:55] Done.
[07.03.18|11:35:55] Eval epoch: 4
/opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/generic/THCStorage.c line=36 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    p.start()
  File "/home/nll/st-gcn-master/processor/processor.py", line 126, in start
    self.test()
  File "/home/nll/st-gcn-master/processor/recognition.py", line 132, in test
    loss_value.append(loss.item())
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/generic/THCStorage.c:36

**Comment by yysijie** [comment]
@nilili89,
Hi, this is a network for classification tasks. I think your dataset should include two class at least.
