### ISSUE TITLE
Error while running demo

### ISSUE THREAD

**Issue by Zzoey** [yysijie/st-gcn#59]
### Code version (Git Hash) and PyTorch version
latest
### Dataset used
Kinetics

### Expected behavior
Result saved on ./data/demo_result

### Actual behavior
1.   File "main.py", line 31, in <module>
    p.start()
  File "/home/paperspace/st-gcn/processor/demo.py", line 61, in start
    pose, _ = utils.video.video_info_parsing(video_info)
  File "/home/paperspace/st-gcn/tools/utils/video.py", line 16, in video_info_parsing
    data_numpy[0, frame_index, :, m] = pose[0::2]
ValueError: cannot copy sequence with size 25 to array axis with dimension 18

After this I changed the value from 18 to 25 in utils.video.py

Network forwad...
2. Traceback (most recent call last):
   File "main.py", line 31, in <module>
    p.start()
  File "/home/paperspace/st-gcn/processor/demo.py", line 69, in start
    output, feature = self.model.extract_feature(data)
  File "/home/paperspace/st-gcn/net/st_gcn.py", line 100, in extract_feature
    x = self.data_bn(x)
  File "/home/paperspace/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/paperspace/python3/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/home/paperspace/python3/lib/python3.6/site-packages/torch/nn/functional.py", line 1194, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 75 elements not 54

### Other comments
Can someone please help ?

**Comment by jay-kob** [comment]
I'm also experiencing the same error on the latest versions of openpose and st-gcn. Any help?

**Comment by yysijie** [comment]
@Zzoey , Sorry for the late reply.
And thanks to the help from @jay-kob.

Yes, Openpose modified their default arguments recently, which results in the error while running the demo. We had fixed this bug according to the advice from @jay-kob.
To avoid similar problems, it is recommended to use [this version](https://github.com/yysijie/openpose) of Openpose.
