### ISSUE TITLE
module 'torch' has no attribute 'float32'

### ISSUE THREAD

**Issue by zswmr** [yysijie/st-gcn#66]
### Code version (Git Hash) and PyTorch version
PyTorch0.4.0
### Dataset used
video i take
### Expected behavior
meet a problem, i does not know how to deal with it ?
### Actual behavior
(pytorch) vetec@vetec:~/Pan/action/st-gcn$ python main.py demo --openpose '/home/vetec/Pan/action/openpose/build'  --video '/home/vetec/Videos/action/001.mp4'  --device 0
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    p = Processor(sys.argv[2:])
  File "/home/vetec/Pan/action/st-gcn/processor/io.py", line 27, in __init__
    self.load_model()
  File "/home/vetec/Pan/action/st-gcn/processor/io.py", line 70, in load_model
    **(self.arg.model_args))
  File "/home/vetec/anaconda3/envs/pytorch/lib/python3.5/site-packages/torchlight-1.0-py3.5.egg/torchlight/io.py", line 53, in load_model
    
  File "/home/vetec/Pan/action/st-gcn/net/st_gcn.py", line 36, in __init__
    A = torch.tensor(self.graph.A, dtype=torch.float32, re

**Comment by yysijie** [comment]
Hi, did you install the Pytorch official release version 0.4.0?
Some earlier versions are also called '0.4.0' version, but it does not include 'float32'.

**Comment by navneetkrc** [comment]
torchtext is the offending …?module?..(not sure what to call it) that causes this error. The authors released torchtext 0.3.1 earlier today (2018-10-11). Installing the previous version restores full functionality:
!{sys.executable} -m pip install torchtext==0.2.3 worked for me
