### ISSUE TITLE
Issues when testing the pretrained model

### ISSUE THREAD

**Issue by LeiWangR** [yysijie/st-gcn#68]
### Code version (Git Hash) and PyTorch version
Mac *CPU*
PyTorch version is 0.4.0
### Dataset used
Kinetics-skeleton
### Expected behavior
To evaluate ST-GCN model pretrained on Kinetics-skeleton
### Actual behavior

**python main.py recognition -c config/st_gcn/kinetics-skeleton/test.yaml**
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    p = Processor(sys.argv[2:])
  File "/Users/ray/st-gcn/processor/processor.py", line 29, in \__init\__
    self.init_environment()
  File "/Users/ray/st-gcn/processor/processor.py", line 38, in init_environment
    super().init_environment()
  File "/Users/ray/st-gcn/processor/io.py", line 62, in init_environment
    torchlight.occupy_gpu(gpus)
  File "/anaconda3/envs/myenv3.6/lib/python3.6/site-packages/torchlight-1.0-py3.6.egg/torchlight/gpu.py", line 35, in occupy_gpu
**RuntimeError: torch.cuda.FloatTensor is not enabled.**
### Other comments
Please let me know if you have some suggestions with that. 

Thank you very much!

**Comment by yjxiong** [comment]
Have you installed the CUDA-enabled PyTorch? The codebase needs GPU to run.
