### ISSUE TITLE
Error while training on a new dataset.

### ISSUE THREAD

**Issue by Zzoey** [yysijie/st-gcn#73]
I have generated the data into the required format by modifying feeder and kinetics_gendata by using my own conversion of poses openpose to json samples.

My new dataset is small compared to kinetics, and when I tried to train, I get, mean_loss as nan and the following error. It would be great if you can help!

[07.28.18|14:36:39] 	mean_loss: nan
[07.28.18|14:36:39] Time consumption:
[07.28.18|14:36:39] Done.
[07.28.18|14:36:39] Training epoch: 1
[07.28.18|14:36:39] 	mean_loss: nan
[07.28.18|14:36:39] Time consumption:
[07.28.18|14:36:39] Done.
[07.28.18|14:36:39] Training epoch: 2
[07.28.18|14:36:39] 	mean_loss: nan
[07.28.18|14:36:39] Time consumption:
[07.28.18|14:36:39] Done.
[07.28.18|14:36:39] The model has been saved as ./work_dir/recognition/kinetics_skeleton/ST_GCN/epoch3_model.pt.
[07.28.18|14:36:39] Eval epoch: 2
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    p.start()
  File "/home/paperspace/st-gcn/processor/processor.py", line 126, in start
    self.test()
  File "/home/paperspace/st-gcn/processor/recognition.py", line 119, in test
    for data, label in loader:
  File "/home/paperspace/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/paperspace/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/paperspace/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/paperspace/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/paperspace/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/paperspace/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 129, in default_collate
    return torch.LongTensor(batch)
TypeError: an integer is required (got type str)

**Comment by yjxiong** [comment]
Your training takes no time for 1 epoch. In most cases this means there is no data fed to the training process. I would suggest you look at you dataset loading and parsing logic.

**Comment by KimJungMin0320** [comment]
Did you solve this problem?
If yes, can you let me know how to handle it?

Regards, JM
